development:
  adapter: postgresql
  database: fesearch_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: fesearch_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: fesearch_production
  pool: 5
  timeout: 5000
